package es.daniela.tfg;

import ij.IJ;

import org.scijava.command.Command;
import org.scijava.plugin.Plugin;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.io.*;
import java.nio.file.Files;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Properties;

@Plugin(type = Command.class, menuPath = "Plugins>Neuron Segmentation>Model Comparison / External Validation")
public class NeuronModelComparisonWindowCommand implements Command {

    private String pythonExe;
    private String inferenceScriptPath;
    private String retrainScriptPath;
    private String compareScriptPath;

    private JFrame frame;

    private JTextField validationDatasetField;
    private JTextField baseModelField;
    private JTextField transferModelField;
    private JTextField outputDirField;

    private JButton selectValidationDatasetButton;
    private JButton selectBaseModelButton;
    private JButton selectTransferModelButton;
    private JButton selectOutputDirButton;
    private JButton runComparisonButton;
    private JButton openOutputDirButton;

    private JCheckBox useHardwareAccelerationCheckBox;

    private JLabel statusLabel;
    private JTextArea logTextArea;

    private JTable metricsTable;
    private DefaultTableModel metricsTableModel;

    private File validationDataYaml;
    private File baseModelFile;
    private File transferLearningModelFile;
    private File outputDir;

    private File logFile;
    private PrintWriter logWriter;

    private boolean comparisonRunning = false;
    private boolean useHardwareAccelerationForValidation = false;

    private static final String CONFIG_DIR_NAME = ".neuron-segmentation-assistant";
    private static final String CONFIG_FILE_NAME = "config.properties";
    private static final String CONFIG_USE_HARDWARE_ACCELERATION = "use_hardware_acceleration";

    @Override
    public void run() {
        SwingUtilities.invokeLater(this::createWindow);
    }

    private void createWindow() {
        loadConfiguration();

        frame = new JFrame("Model Comparison / External Validation");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setSize(980, 720);
        frame.setLayout(new BorderLayout(8, 8));

        frame.add(createMainPanel(), BorderLayout.CENTER);
        frame.add(createBottomPanel(), BorderLayout.SOUTH);

        frame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                appendLog("Closing model comparison window.");
                closeLogFile();
            }
        });

        baseModelFile = getBaseModelFromConfiguration();
        outputDir = getDefaultOutputDir();

        updateFields();
        updateStatus("Ready. Select an external validation dataset to compare models.");
        updateButtonState();

        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    private JPanel createMainPanel() {
        JPanel panel = new JPanel(new BorderLayout(8, 8));
        panel.setBorder(BorderFactory.createEmptyBorder(8, 8, 8, 8));

        JPanel topPanel = new JPanel(new BorderLayout(8, 8));

        JPanel infoPanel = new JPanel(new BorderLayout());
        infoPanel.setBorder(BorderFactory.createTitledBorder("External validation"));

        JLabel infoLabel = new JLabel(
                "<html>" +
                        "Compare the base YOLO model against an adapted model using an external " +
                        "validation dataset annotated in YOLO format.<br><br>" +
                        "You can select either a prepared <b>data.yaml</b> file or an image folder " +
                        "containing corrected annotations generated by the transfer learning assistant." +
                        "</html>"
        );

        infoLabel.setBorder(BorderFactory.createEmptyBorder(6, 6, 6, 6));
        infoPanel.add(infoLabel, BorderLayout.CENTER);

        topPanel.add(infoPanel, BorderLayout.NORTH);
        topPanel.add(createConfigurationPanel(), BorderLayout.CENTER);

        JSplitPane splitPane = new JSplitPane(
                JSplitPane.VERTICAL_SPLIT,
                createResultsPanel(),
                createLogPanel()
        );

        splitPane.setResizeWeight(0.58);
        splitPane.setDividerLocation(310);
        splitPane.setOneTouchExpandable(true);

        panel.add(topPanel, BorderLayout.NORTH);
        panel.add(splitPane, BorderLayout.CENTER);

        return panel;
    }

    private JPanel createConfigurationPanel() {
        JPanel panel = new JPanel(new GridBagLayout());
        panel.setBorder(BorderFactory.createTitledBorder("Inputs"));

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(4, 6, 4, 6);
        gbc.fill = GridBagConstraints.HORIZONTAL;

        validationDatasetField = createReadOnlyTextField();
        baseModelField = createReadOnlyTextField();
        transferModelField = createReadOnlyTextField();
        outputDirField = createReadOnlyTextField();

        selectValidationDatasetButton = new JButton("Select...");
        selectBaseModelButton = new JButton("Change...");
        selectTransferModelButton = new JButton("Select...");
        selectOutputDirButton = new JButton("Change...");

        selectValidationDatasetButton.addActionListener(e -> selectValidationDataset());
        selectBaseModelButton.addActionListener(e -> selectBaseModel());
        selectTransferModelButton.addActionListener(e -> selectTransferLearningModel());
        selectOutputDirButton.addActionListener(e -> selectOutputDir());

        useHardwareAccelerationCheckBox = new JCheckBox("Use hardware acceleration");
        useHardwareAccelerationCheckBox.setSelected(useHardwareAccelerationForValidation);
        useHardwareAccelerationCheckBox.setToolTipText(
                "If enabled, validation will request CUDA or Apple MPS when available."
        );

        useHardwareAccelerationCheckBox.addActionListener(e -> {
            saveHardwareAccelerationPreference(useHardwareAccelerationCheckBox.isSelected());

            if (useHardwareAccelerationCheckBox.isSelected()) {
                updateStatus("Hardware acceleration enabled for validation.");
            } else {
                updateStatus("CPU validation selected.");
            }
        });

        addInputRow(panel, gbc, 0, "Validation dataset:", validationDatasetField, selectValidationDatasetButton);
        addInputRow(panel, gbc, 1, "Base model:", baseModelField, selectBaseModelButton);
        addInputRow(panel, gbc, 2, "Adapted model:", transferModelField, selectTransferModelButton);
        addInputRow(panel, gbc, 3, "Output folder:", outputDirField, selectOutputDirButton);

        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.gridwidth = 2;
        panel.add(useHardwareAccelerationCheckBox, gbc);

        JPanel actionsPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));

        runComparisonButton = new JButton("Run comparison");
        runComparisonButton.setFont(runComparisonButton.getFont().deriveFont(Font.BOLD));
        runComparisonButton.addActionListener(e -> runComparison());

        openOutputDirButton = new JButton("Open output folder");
        openOutputDirButton.addActionListener(e -> openOutputDirectory());

        actionsPanel.add(openOutputDirButton);
        actionsPanel.add(runComparisonButton);

        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.weightx = 1.0;
        gbc.gridwidth = 3;
        panel.add(actionsPanel, gbc);

        return panel;
    }

    private JTextField createReadOnlyTextField() {
        JTextField textField = new JTextField();
        textField.setEditable(false);
        textField.setHorizontalAlignment(JTextField.LEFT);
        return textField;
    }

    private void addInputRow(
            JPanel panel,
            GridBagConstraints gbc,
            int row,
            String label,
            JTextField field,
            JButton button
    ) {
        gbc.gridx = 0;
        gbc.gridy = row;
        gbc.weightx = 0.0;
        gbc.gridwidth = 1;
        panel.add(new JLabel(label), gbc);

        gbc.gridx = 1;
        gbc.gridy = row;
        gbc.weightx = 1.0;
        gbc.gridwidth = 1;
        panel.add(field, gbc);

        gbc.gridx = 2;
        gbc.gridy = row;
        gbc.weightx = 0.0;
        gbc.gridwidth = 1;
        panel.add(button, gbc);
    }

    private JPanel createResultsPanel() {
        JPanel panel = new JPanel(new BorderLayout(4, 4));
        panel.setBorder(BorderFactory.createTitledBorder("Metrics"));

        metricsTableModel = new DefaultTableModel(
                new Object[]{"Metric", "Base model", "Adapted model", "Difference (adapted - base)"},
                0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        metricsTable = new JTable(metricsTableModel);
        metricsTable.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        metricsTable.getTableHeader().setReorderingAllowed(false);

        panel.add(new JScrollPane(metricsTable), BorderLayout.CENTER);

        JLabel hintLabel = new JLabel(
                "The CSV file model_comparison_metrics.csv is generated in the selected output folder."
        );
        hintLabel.setBorder(BorderFactory.createEmptyBorder(4, 4, 4, 4));
        panel.add(hintLabel, BorderLayout.SOUTH);

        return panel;
    }

    private JPanel createLogPanel() {
        JPanel panel = new JPanel(new BorderLayout(4, 4));
        panel.setBorder(BorderFactory.createTitledBorder("Log"));

        logTextArea = new JTextArea(10, 100);
        logTextArea.setEditable(false);
        logTextArea.setLineWrap(false);
        logTextArea.setFont(new Font(Font.MONOSPACED, Font.PLAIN, 11));

        panel.add(new JScrollPane(logTextArea), BorderLayout.CENTER);

        return panel;
    }

    private JPanel createBottomPanel() {
        JPanel panel = new JPanel(new BorderLayout(4, 4));
        panel.setBorder(BorderFactory.createEmptyBorder(4, 8, 8, 8));

        statusLabel = new JLabel("Ready.");
        statusLabel.setBorder(BorderFactory.createEmptyBorder(4, 4, 4, 4));

        panel.add(statusLabel, BorderLayout.CENTER);

        return panel;
    }

    private void selectValidationDataset() {
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        int result = chooser.showOpenDialog(frame);

        if (result != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File selected = chooser.getSelectedFile();

        try {
            File dataYaml;

            if (selected.isDirectory()) {
                File directDataYaml = new File(selected, "data.yaml");

                if (directDataYaml.exists()) {
                    dataYaml = directDataYaml;
                } else {
                    dataYaml = buildValidationDatasetFromCorrectedAnnotations(selected);
                }
            } else {
                dataYaml = selected;
            }

            if (!dataYaml.exists() || !dataYaml.getName().equals("data.yaml")) {
                IJ.error(
                        "Invalid validation dataset",
                        "Please select either:\n\n" +
                                "- a YOLO data.yaml file\n" +
                                "- a YOLO dataset folder containing data.yaml\n" +
                                "- an image folder containing neuron_transfer_learning/annotations"
                );
                return;
            }

            validationDataYaml = dataYaml;

            if (outputDir == null) {
                outputDir = new File(dataYaml.getParentFile(), "model_comparison_output");
            }

            initializeLogFile();
            appendLog("Validation dataset selected: " + validationDataYaml.getAbsolutePath());

            updateFields();
            updateStatus("Validation dataset selected.");
            updateButtonState();

        } catch (Exception e) {
            logError("Could not prepare validation dataset: " + e.getMessage());
            IJ.handleException(e);
            updateStatus("Could not prepare validation dataset.");
        }
    }

    private File buildValidationDatasetFromCorrectedAnnotations(File imageFolder) throws IOException {
        File transferDir = new File(imageFolder, "neuron_transfer_learning");
        File annotationsDir = new File(transferDir, "annotations");

        if (!annotationsDir.exists()) {
            throw new IOException(
                    "No neuron_transfer_learning/annotations folder found in:\n" +
                            imageFolder.getAbsolutePath()
            );
        }

        File validationDatasetDir = new File(transferDir, "yolo_validation_dataset");
        File imagesValDir = new File(validationDatasetDir, "images/val");
        File labelsValDir = new File(validationDatasetDir, "labels/val");

        imagesValDir.mkdirs();
        labelsValDir.mkdirs();

        clearDirectory(imagesValDir);
        clearDirectory(labelsValDir);

        File[] files = imageFolder.listFiles();

        if (files == null) {
            throw new IOException("No files found in selected folder.");
        }

        int count = 0;

        for (File imageFile : files) {
            if (!imageFile.isFile() || !isSupportedImage(imageFile)) {
                continue;
            }

            String imageBaseName = getBaseName(imageFile);
            File latestAnnotation = getLatestAnnotationFileForValidation(annotationsDir, imageBaseName);

            if (latestAnnotation == null || !latestAnnotation.exists()) {
                appendLog("Skipping image without corrected annotation: " + imageFile.getName());
                continue;
            }

            String extension = getExtension(imageFile);
            File targetImage = new File(imagesValDir, imageBaseName + extension);
            File targetLabel = new File(labelsValDir, imageBaseName + ".txt");

            Files.copy(imageFile.toPath(), targetImage.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
            Files.copy(latestAnnotation.toPath(), targetLabel.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);

            appendLog("Validation sample added: " + imageFile.getName());
            count++;
        }

        if (count == 0) {
            throw new IOException(
                    "No corrected annotations found.\n\n" +
                            "Open the Transfer Learning Assistant, correct images and save corrections first."
            );
        }

        File dataYaml = new File(validationDatasetDir, "data.yaml");

        try (PrintWriter writer = new PrintWriter(new FileWriter(dataYaml))) {
            writer.println("path: \"" + validationDatasetDir.getAbsolutePath().replace("\\", "/") + "\"");
            writer.println("train: images/val");
            writer.println("val: images/val");
            writer.println("names:");
            writer.println("  0: neuron");
        }

        appendLog("Validation dataset built with " + count + " corrected images.");
        appendLog("Validation data.yaml: " + dataYaml.getAbsolutePath());

        return dataYaml;
    }

    private boolean isSupportedImage(File file) {
        if (file == null || !file.isFile()) {
            return false;
        }

        String name = file.getName();
        String lowerName = name.toLowerCase(java.util.Locale.ROOT);

        if (name.startsWith("._") ||
                name.startsWith(".") ||
                lowerName.equals("thumbs.db") ||
                lowerName.equals("desktop.ini") ||
                lowerName.equals(".ds_store")) {
            return false;
        }

        if (file.isHidden()) {
            return false;
        }

        return lowerName.endsWith(".png") ||
                lowerName.endsWith(".jpg") ||
                lowerName.endsWith(".jpeg") ||
                lowerName.endsWith(".tif") ||
                lowerName.endsWith(".tiff");
    }

    private String getBaseName(File file) {
        String name = file.getName();
        int dot = name.lastIndexOf(".");

        if (dot > 0) {
            name = name.substring(0, dot);
        }

        return sanitizeFileName(name);
    }

    private String sanitizeFileName(String name) {
        return name.replaceAll("[^a-zA-Z0-9._-]", "_");
    }

    private String getExtension(File file) {
        String name = file.getName();
        int dot = name.lastIndexOf(".");

        if (dot >= 0) {
            return name.substring(dot).toLowerCase(java.util.Locale.ROOT);
        }

        return ".png";
    }

    private File getLatestAnnotationFileForValidation(File annotationsDir, String imageBaseName) {
        File annotationFolder = new File(annotationsDir, imageBaseName);

        if (!annotationFolder.exists()) {
            return null;
        }

        File[] files = annotationFolder.listFiles((dir, name) ->
                name.startsWith("annotation_") && name.endsWith(".txt")
        );

        if (files == null || files.length == 0) {
            return null;
        }

        File latest = files[0];

        for (File file : files) {
            if (file.getName().compareTo(latest.getName()) > 0) {
                latest = file;
            }
        }

        return latest;
    }

    private void clearDirectory(File directory) throws IOException {
        if (directory == null || !directory.exists()) {
            return;
        }

        File[] files = directory.listFiles();

        if (files == null) {
            return;
        }

        for (File file : files) {
            if (file.isDirectory()) {
                clearDirectory(file);

                if (!file.delete()) {
                    appendLog("Could not delete directory: " + file.getAbsolutePath());
                }
            } else {
                Files.deleteIfExists(file.toPath());
            }
        }
    }

    private void selectBaseModel() {
        File selected = chooseModelFile(baseModelFile);

        if (selected == null) {
            return;
        }

        baseModelFile = selected;
        appendLog("Base model selected: " + selected.getAbsolutePath());

        updateFields();
        updateStatus("Base model selected.");
        updateButtonState();
    }

    private void selectTransferLearningModel() {
        File selected = chooseModelFile(transferLearningModelFile);

        if (selected == null) {
            return;
        }

        transferLearningModelFile = selected;
        appendLog("Adapted model selected: " + selected.getAbsolutePath());

        updateFields();
        updateStatus("Adapted model selected.");
        updateButtonState();
    }

    private File chooseModelFile(File currentFile) {
        JFileChooser chooser = new JFileChooser();

        if (currentFile != null && currentFile.getParentFile() != null && currentFile.getParentFile().exists()) {
            chooser.setCurrentDirectory(currentFile.getParentFile());
        }

        int result = chooser.showOpenDialog(frame);

        if (result != JFileChooser.APPROVE_OPTION) {
            return null;
        }

        File selected = chooser.getSelectedFile();

        if (!selected.exists() || !selected.getName().toLowerCase().endsWith(".pt")) {
            IJ.error("Please select a valid .pt model file.");
            return null;
        }

        return selected;
    }

    private void selectOutputDir() {
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        if (outputDir != null && outputDir.exists()) {
            chooser.setCurrentDirectory(outputDir);
        }

        int result = chooser.showOpenDialog(frame);

        if (result != JFileChooser.APPROVE_OPTION) {
            return;
        }

        outputDir = chooser.getSelectedFile();

        appendLog("Output folder selected: " + outputDir.getAbsolutePath());

        updateFields();
        updateStatus("Output folder selected.");
        updateButtonState();
    }

    private void runComparison() {
        if (pythonExe == null || pythonExe.trim().isEmpty()) {
            IJ.error("Python executable is not configured. Please run the installer first.");
            return;
        }

        if (compareScriptPath == null || compareScriptPath.trim().isEmpty()) {
            IJ.error("Comparison script is not configured.");
            return;
        }

        File pythonFile = new File(pythonExe);
        File compareScript = new File(compareScriptPath);

        if (!pythonFile.exists()) {
            IJ.error("Python executable not found:\n" + pythonExe);
            return;
        }

        if (!compareScript.exists()) {
            IJ.error(
                    "Comparison script not found:\n" +
                            compareScript.getAbsolutePath() +
                            "\n\nPlace compare_models.py next to retrain_model.py or add compare_script to config.properties."
            );
            return;
        }

        if (validationDataYaml == null || !validationDataYaml.exists()) {
            IJ.error("Please select a validation data.yaml first.");
            return;
        }

        File datasetRoot = validationDataYaml.getParentFile();

        File imagesTrainDir = new File(datasetRoot, "images/train");
        File labelsTrainDir = new File(datasetRoot, "labels/train");
        File imagesValDir = new File(datasetRoot, "images/val");
        File labelsValDir = new File(datasetRoot, "labels/val");

        boolean hasTrainStructure = imagesTrainDir.exists() && labelsTrainDir.exists();
        boolean hasValStructure = imagesValDir.exists() && labelsValDir.exists();

        if (!hasTrainStructure && !hasValStructure) {
            IJ.error(
                    "Invalid validation dataset",
                    "The selected dataset must contain either:\n\n" +
                            "images/val and labels/val\n\n" +
                            "or:\n\n" +
                            "images/train and labels/train\n\n" +
                            "Please generate or select a valid YOLO dataset."
            );
            return;
        }

        File selectedImagesDir = hasValStructure ? imagesValDir : imagesTrainDir;
        File selectedLabelsDir = hasValStructure ? labelsValDir : labelsTrainDir;

        int imageCount = countSupportedImages(selectedImagesDir);
        int labelCount = countTxtFiles(selectedLabelsDir);

        if (imageCount == 0 || labelCount == 0) {
            IJ.error(
                    "Empty validation dataset",
                    "The selected validation dataset does not contain valid image/label pairs.\n\n" +
                            "Images found: " + imageCount + "\n" +
                            "Labels found: " + labelCount + "\n\n" +
                            "If you selected an image folder, make sure corrections were saved first."
            );
            return;
        }

        if (baseModelFile == null || !baseModelFile.exists()) {
            IJ.error("Please select a valid base model.");
            return;
        }

        if (transferLearningModelFile == null || !transferLearningModelFile.exists()) {
            IJ.error("Please select a valid adapted model.");
            return;
        }

        if (outputDir == null) {
            outputDir = getDefaultOutputDir();
        }

        if (outputDir == null) {
            IJ.error("Please select an output folder.");
            return;
        }

        if (!outputDir.exists() && !outputDir.mkdirs()) {
            IJ.error("Could not create output folder:\n" + outputDir.getAbsolutePath());
            return;
        }

        initializeLogFile();

        metricsTableModel.setRowCount(0);

        comparisonRunning = true;
        updateStatus("Running external validation comparison...");
        updateButtonState();

        boolean useHardwareAcceleration =
                useHardwareAccelerationCheckBox != null && useHardwareAccelerationCheckBox.isSelected();

        new Thread(() -> {
            try {
                List<String> command = new ArrayList<>();

                command.add(pythonExe);
                command.add("-u");
                command.add(compareScriptPath);
                command.add(baseModelFile.getAbsolutePath());
                command.add(transferLearningModelFile.getAbsolutePath());
                command.add(validationDataYaml.getAbsolutePath());
                command.add(outputDir.getAbsolutePath());

                String selectedDevice;

                if (useHardwareAcceleration) {
                    selectedDevice = "auto_acceleration";
                } else {
                    selectedDevice = "cpu";
                }

                command.add(selectedDevice);

                appendLogSeparator();
                appendLog("Model comparison started.");
                appendLog("Validation data.yaml: " + validationDataYaml.getAbsolutePath());
                appendLog("Base model: " + baseModelFile.getAbsolutePath());
                appendLog("Adapted model: " + transferLearningModelFile.getAbsolutePath());
                appendLog("Output folder: " + outputDir.getAbsolutePath());
                appendLog("Requested validation device: " + selectedDevice);
                appendLog("Command: " + String.join(" ", command));
                appendLogSeparator();

                ProcessBuilder pb = new ProcessBuilder(command);
                pb.redirectErrorStream(true);

                Process process = pb.start();

                try (BufferedReader reader = new BufferedReader(
                        new InputStreamReader(process.getInputStream()))) {

                    String line;

                    while ((line = reader.readLine()) != null) {
                        logPython(line);
                    }
                }

                int exitCode = process.waitFor();

                if (exitCode != 0) {
                    throw new RuntimeException("Model comparison failed with exit code " + exitCode);
                }

                File metricsCsv = new File(outputDir, "model_comparison_metrics.csv");
                List<String[]> rows = readMetricsCsv(metricsCsv);

                SwingUtilities.invokeLater(() -> {
                    comparisonRunning = false;
                    fillMetricsTable(rows);
                    updateStatus("Model comparison completed.");
                    updateButtonState();

                    appendLog("Model comparison completed successfully.");
                    appendLog("Metrics CSV: " + metricsCsv.getAbsolutePath());

                    IJ.showMessage(
                            "Model comparison completed",
                            "Metrics saved to:\n" + metricsCsv.getAbsolutePath()
                    );
                });

            } catch (Exception e) {
                logError("Model comparison failed: " + e.getMessage());
                IJ.handleException(e);

                SwingUtilities.invokeLater(() -> {
                    comparisonRunning = false;
                    updateStatus("Model comparison failed.");
                    updateButtonState();
                });
            }
        }).start();
    }

    private int countSupportedImages(File directory) {
        if (directory == null || !directory.exists()) {
            return 0;
        }

        File[] files = directory.listFiles();

        if (files == null) {
            return 0;
        }

        int count = 0;

        for (File file : files) {
            if (file.isFile() && isSupportedImage(file)) {
                count++;
            }
        }

        return count;
    }

    private int countTxtFiles(File directory) {
        if (directory == null || !directory.exists()) {
            return 0;
        }

        File[] files = directory.listFiles();

        if (files == null) {
            return 0;
        }

        int count = 0;

        for (File file : files) {
            if (file.isFile() && file.getName().toLowerCase(java.util.Locale.ROOT).endsWith(".txt")) {
                count++;
            }
        }

        return count;
    }

    private List<String[]> readMetricsCsv(File csvFile) throws IOException {
        List<String[]> rows = new ArrayList<>();

        if (!csvFile.exists()) {
            throw new IOException("Metrics CSV not found: " + csvFile.getAbsolutePath());
        }

        try (BufferedReader reader = new BufferedReader(new FileReader(csvFile))) {
            String line = reader.readLine();

            while ((line = reader.readLine()) != null) {
                String[] parts = splitCsvLine(line);

                if (parts.length >= 4) {
                    rows.add(new String[]{parts[0], parts[1], parts[2], parts[3]});
                }
            }
        }

        return rows;
    }

    private String[] splitCsvLine(String line) {
        List<String> values = new ArrayList<>();
        StringBuilder current = new StringBuilder();

        boolean inQuotes = false;

        for (int i = 0; i < line.length(); i++) {
            char c = line.charAt(i);

            if (c == '"') {
                inQuotes = !inQuotes;
            } else if (c == ',' && !inQuotes) {
                values.add(current.toString());
                current.setLength(0);
            } else {
                current.append(c);
            }
        }

        values.add(current.toString());

        return values.toArray(new String[0]);
    }

    private void fillMetricsTable(List<String[]> rows) {
        metricsTableModel.setRowCount(0);

        for (String[] row : rows) {
            metricsTableModel.addRow(row);
        }
    }

    private void openOutputDirectory() {
        if (outputDir == null || !outputDir.exists()) {
            IJ.error("Output folder does not exist yet.");
            return;
        }

        try {
            Desktop.getDesktop().open(outputDir);
        } catch (Exception e) {
            IJ.handleException(e);
        }
    }

    private void loadConfiguration() {
        try {
            File configFile = new File(
                    System.getProperty("user.home"),
                    CONFIG_DIR_NAME + "/" + CONFIG_FILE_NAME
            );

            if (!configFile.exists()) {
                IJ.error(
                        "Configuration not found",
                        "Config file not found:\n" +
                                configFile.getAbsolutePath() +
                                "\n\nPlease run the installer first."
                );
                return;
            }

            Properties properties = new Properties();

            try (FileInputStream fis = new FileInputStream(configFile)) {
                properties.load(fis);
            }

            pythonExe = properties.getProperty("python");
            inferenceScriptPath = properties.getProperty("script");
            retrainScriptPath = properties.getProperty("retrain_script");

            compareScriptPath = properties.getProperty("compare_script");

            if (compareScriptPath == null || compareScriptPath.trim().isEmpty()) {
                compareScriptPath = inferCompareScriptPath();
            }

            useHardwareAccelerationForValidation = Boolean.parseBoolean(
                    properties.getProperty(CONFIG_USE_HARDWARE_ACCELERATION, "false")
            );

            appendLog("Loaded config file: " + configFile.getAbsolutePath());
            appendLog("Loaded Python executable: " + pythonExe);
            appendLog("Loaded inference script: " + inferenceScriptPath);
            appendLog("Loaded retraining script: " + retrainScriptPath);
            appendLog("Loaded comparison script: " + compareScriptPath);

            if (pythonExe == null || pythonExe.trim().isEmpty()) {
                IJ.error("Configuration error", "Missing property: python");
            }

            if (compareScriptPath == null || compareScriptPath.trim().isEmpty()) {
                IJ.error("Configuration error", "Could not resolve compare_models.py");
            }

        } catch (Exception e) {
            logError("Could not load configuration: " + e.getMessage());
            IJ.handleException(e);
        }
    }

    private String inferCompareScriptPath() {
        if (retrainScriptPath != null && !retrainScriptPath.trim().isEmpty()) {
            File retrainScript = new File(retrainScriptPath);

            if (retrainScript.getParentFile() != null) {
                return new File(retrainScript.getParentFile(), "compare_models.py").getAbsolutePath();
            }
        }

        if (inferenceScriptPath != null && !inferenceScriptPath.trim().isEmpty()) {
            File inferenceScript = new File(inferenceScriptPath);

            if (inferenceScript.getParentFile() != null) {
                return new File(inferenceScript.getParentFile(), "compare_models.py").getAbsolutePath();
            }
        }

        return null;
    }

    private File getBaseModelFromConfiguration() {
        if (inferenceScriptPath == null || inferenceScriptPath.trim().isEmpty()) {
            return null;
        }

        File inferenceScript = new File(inferenceScriptPath);

        if (inferenceScript.getParentFile() == null) {
            return null;
        }

        File baseModel = new File(inferenceScript.getParentFile(), "models/best.pt");

        if (baseModel.exists()) {
            return baseModel;
        }

        return null;
    }

    private File getDefaultOutputDir() {
        if (validationDataYaml != null && validationDataYaml.getParentFile() != null) {
            return new File(validationDataYaml.getParentFile(), "model_comparison_output");
        }

        return new File(
                System.getProperty("user.home"),
                CONFIG_DIR_NAME + "/model_comparison_output"
        );
    }

    private void saveHardwareAccelerationPreference(boolean useHardwareAcceleration) {
        useHardwareAccelerationForValidation = useHardwareAcceleration;

        File configFile = new File(
                System.getProperty("user.home"),
                CONFIG_DIR_NAME + "/" + CONFIG_FILE_NAME
        );

        try {
            Properties properties = new Properties();

            if (configFile.exists()) {
                try (FileInputStream fis = new FileInputStream(configFile)) {
                    properties.load(fis);
                }
            }

            properties.setProperty(
                    CONFIG_USE_HARDWARE_ACCELERATION,
                    Boolean.toString(useHardwareAcceleration)
            );

            configFile.getParentFile().mkdirs();

            try (FileOutputStream fos = new FileOutputStream(configFile)) {
                properties.store(fos, "Neuron Segmentation Assistant configuration");
            }

            appendLog("Hardware acceleration preference saved: " + useHardwareAcceleration);

        } catch (Exception e) {
            logError("Could not save hardware acceleration preference: " + e.getMessage());
            IJ.handleException(e);
        }
    }

    private void updateFields() {
        if (validationDatasetField != null) {
            if (validationDataYaml != null && validationDataYaml.getParentFile() != null) {
                validationDatasetField.setText(validationDataYaml.getParentFile().getAbsolutePath());
                validationDatasetField.setToolTipText(validationDataYaml.getAbsolutePath());
            } else {
                validationDatasetField.setText("Not selected");
                validationDatasetField.setToolTipText(null);
            }
        }

        if (baseModelField != null) {
            baseModelField.setText(fileToText(baseModelFile));
            baseModelField.setToolTipText(fileToTooltip(baseModelFile));
        }

        if (transferModelField != null) {
            transferModelField.setText(fileToText(transferLearningModelFile));
            transferModelField.setToolTipText(fileToTooltip(transferLearningModelFile));
        }

        if (outputDirField != null) {
            outputDirField.setText(fileToText(outputDir));
            outputDirField.setToolTipText(fileToTooltip(outputDir));
        }
    }

    private String fileToText(File file) {
        if (file == null) {
            return "Not selected";
        }

        File parent = file.getParentFile();

        if (parent != null) {
            return parent.getName() + "/" + file.getName();
        }

        return file.getName();
    }

    private String fileToTooltip(File file) {
        if (file == null) {
            return null;
        }

        return file.getAbsolutePath();
    }

    private void updateButtonState() {
        boolean ready =
                pythonExe != null &&
                        compareScriptPath != null &&
                        validationDataYaml != null &&
                        baseModelFile != null &&
                        transferLearningModelFile != null &&
                        outputDir != null;

        selectValidationDatasetButton.setEnabled(!comparisonRunning);
        selectBaseModelButton.setEnabled(!comparisonRunning);
        selectTransferModelButton.setEnabled(!comparisonRunning);
        selectOutputDirButton.setEnabled(!comparisonRunning);
        runComparisonButton.setEnabled(ready && !comparisonRunning);
        openOutputDirButton.setEnabled(outputDir != null && outputDir.exists() && !comparisonRunning);

        if (useHardwareAccelerationCheckBox != null) {
            useHardwareAccelerationCheckBox.setEnabled(!comparisonRunning);
        }
    }

    private void updateStatus(String message) {
        if (statusLabel != null) {
            statusLabel.setText(message);
        }

        appendLog("STATUS", message);
    }

    private void initializeLogFile() {
        closeLogFile();

        if (outputDir == null) {
            return;
        }

        try {
            File logsDir = new File(outputDir, "logs");

            if (!logsDir.exists() && !logsDir.mkdirs()) {
                logWarning("Could not create logs directory: " + logsDir.getAbsolutePath());
                return;
            }

            String timestamp = new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date());

            logFile = new File(
                    logsDir,
                    "model_comparison_session_" + timestamp + ".log"
            );

            logWriter = new PrintWriter(new FileWriter(logFile, true), true);

            appendLogSeparator();
            appendLog("Log file created: " + logFile.getAbsolutePath());
            appendLogSeparator();

        } catch (Exception e) {
            logError("Could not initialize log file: " + e.getMessage());
            IJ.handleException(e);
        }
    }

    private void closeLogFile() {
        if (logWriter != null) {
            logWriter.flush();
            logWriter.close();
            logWriter = null;
        }
    }

    private String getCurrentTimestampForLog() {
        return new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
    }

    private void appendLogSeparator() {
        appendLog("SYSTEM", "------------------------------------------------------------");
    }

    private synchronized void appendLog(String message) {
        appendLog("INFO", message);
    }

    private synchronized void appendLog(String level, String message) {
        String timestampedMessage =
                "[" + getCurrentTimestampForLog() + "] " +
                        "[" + level + "] " +
                        message;

        if (logTextArea != null) {
            SwingUtilities.invokeLater(() -> {
                logTextArea.append(timestampedMessage + "\n");
                logTextArea.setCaretPosition(logTextArea.getDocument().getLength());
            });
        }

        if (logWriter != null) {
            logWriter.println(timestampedMessage);
            logWriter.flush();
        }
    }

    private void logWarning(String message) {
        appendLog("WARNING", message);
    }

    private void logError(String message) {
        appendLog("ERROR", message);
    }

    private void logPython(String message) {
        appendLog("PYTHON", message);
    }
}
